name: APIs.io Vocabularies
description: Advanced vocabulary search across resources, actions, personas, domains, and schemas.
image: https://kinlane-productions2.s3.amazonaws.com/apis-json/apis-json-logo.jpg
url: https://vocabularies.apis.io

node: website
nav_active: more

keywords:
  - APIs
  - Search
  - Discovery

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "scripts"]

github_org: api-search
github_repo: vocabularies
