name: APIs.io Vocabularies
description: Advanced vocabulary search across resources, actions, personas, domains, and schemas.
image: https://apis.io/assets/branding/apisio-social-card.png
url: https://vocabularies.apis.io

node: website
nav_active: more

keywords:
  - APIs
  - Search
  - Discovery

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "scripts"]
include: [".well-known"]

github_org: api-search
github_repo: vocabularies
